spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fixed_asset?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:fixed_asset}
    password: ${DB_PASSWORD:fixed_asset}
  flyway:
    enabled: true

app:
  cache:
    provider: redis

server:
  port: 8081
